hard_skills = [
    # Languages
    "Java",
    "Python",
    "JavaScript",
    "TypeScript",
    "C#",
    "C++",
    "C",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "PHP",
    "Ruby",
    "Scala",
    "Objective-C",
    "R",
    "MATLAB",
    "Perl",
    # Web frameworks & libraries
    "Spring Boot",
    "Spring",
    "Hibernate",
    "Struts",
    "ASP.NET",
    "Django",
    "Flask",
    "FastAPI",
    "Angular",
    "React.js",
    "Vue.js",
    "Next.js",
    "Nuxt.js",
    "Svelte",
    "Bootstrap",
    "Tailwind CSS",
    # Mobile
    "Android",
    "iOS",
    "React Native",
    "Flutter",
    "Xamarin",
    # Databases
    "SQL",
    "PostgreSQL",
    "MySQL",
    "MariaDB",
    "Oracle DB",
    "SQL Server",
    "MongoDB",
    "Cassandra",
    "Redis",
    "Elasticsearch",
    "Neo4j",
    "Firebase",
    # Cloud
    "AWS",
    "Azure",
    "Google Cloud",
    "Heroku",
    "DigitalOcean",
    "OpenStack",
    # DevOps / CI/CD
    "Docker",
    "Kubernetes",
    "Helm",
    "Terraform",
    "Ansible",
    "Chef",
    "Puppet",
    "Jenkins",
    "GitLab CI",
    "GitHub Actions",
    "CircleCI",
    # Testing
    "JUnit",
    "Mockito",
    "Selenium",
    "Cypress",
    "Playwright",
    "Postman",
    "JUnit5",
    # Other technologies
    "GraphQL",
    "gRPC",
    "REST",
    "SOAP",
    "Microservices",
    "Event-driven architecture",
    "Kafka",
    "RabbitMQ",
    "ActiveMQ",
    "WebSockets",
    # Security
    "OAuth2",
    "JWT",
    "OpenID Connect",
    "Keycloak",
]

soft_skills = [
    "communication",
    "teamwork",
    "problem solving",
    "critical thinking",
    "adaptability",
    "creativity",
    "decision making",
    "time management",
    "leadership",
    "emotional intelligence",
    "conflict resolution",
    "mentoring",
    "collaboration",
    "presentation skills",
    "negotiation",
    "stress management",
    "initiative",
    "accountability",
    "responsibility",
    "attention to detail",
]

tools = [
    # Project management / methodologies
    "Scrum",
    "Kanban",
    "Agile",
    "SAFe",
    "XP",
    "Waterfall",
    "Lean",
    "Prince2",
    "ITIL",
    "DevOps",
    "CI/CD",
    # Collaboration tools
    "Jira",
    "Confluence",
    "Trello",
    "Asana",
    "Slack",
    "MS Teams",
    "Miro",
    "Notion",
    # Version control
    "Git",
    "GitHub",
    "GitLab",
    "Bitbucket",
    "SVN",
    # Monitoring / logging
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "Splunk",
    "Datadog",
    "New Relic",
    # Build tools
    "Maven",
    "Gradle",
    "Ant",
    "Webpack",
    "Vite",
    "NPM",
    "Yarn",
    # OS & environments
    "Linux",
    "Unix",
    "Windows Server",
    "MacOS",
    "Bash",
    "PowerShell",
    # Certifications
    "AWS Certified Solutions Architect",
    "Azure Fundamentals",
    "Certified Kubernetes Administrator",
    "PMP",
    "Scrum Master",
    "TOGAF",
    "CISSP",
]
